name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0b630951ad0ec4608cff6cb605777fa99562a0a80c654ee96ae0f1ef60d3c08"

[versions]
forge = "40.1.69"
minecraft = "1.18.2"
