name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d521ed8af227c199c4728933085e315722066aeb6bb3e4d4a2cd5e96f3738cb"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
