name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f504911134264a92257a601f553dfaf9f97b111a8938dd2ef1002523d58a933"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
