name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35ee5ce8447162ada2b1c10e7dafa68afda4905a113dfa88733311303401cc36"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
