name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a177667b74fbf332fe3c1b14989512b24e7ad24b5a088c09a6253cf45486ceb3"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
