name = "Compression"
author = "Nyagi"
version = "pre-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace6f3f37e1da331f95a1da6b8f5d91010bff42803065790e10bb5591b3d2fef"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
